# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
#permalink:           pretty
#permalink: /:categories/:title:output_ext
permalink: none

# Setup
title:               'Everyday normal hacker'
tagline:             data science and coding
description:         # <a href="link to linkedin" target="_blank">ask for Polish language version</a>
                     <br /> 
                     <br />     
#                    <img src="image.jpg" alt="My Logo" WIDTH=400 HEIGHT=400>                      
#                    English language version
# 'A reserved blog that places the utmost gravity on content. Made by <a href="link to linkedin" target="_blank">@someone</a>.'
url:                 https://john-smith-889.github.io/blog-development/
# url:               https://john-smith-889.github.io/blog-development/  
#<!-- only this code works in local:  -->
#baseurl:             ''
#<!-- only this code works in prod:  -->
baseurl:             '/blog-development'
#baseurl:             '/blog'

# Plugins:
plugins:
  - jekyll-paginate
paginate:             5
#paginate:            5

# About/contact
author:              John Smith

# Custom vars
version:             1.0.

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: john-smith-889-github-io
